[signals.general]
currency = "NZD_2023"
basis    = "fuel_MWh"
scope    = "Edendale_Southland_central"

[signals.epochs."2020"]
year_start = 2020
year_end   = 2023
coal_price_nzd_per_MWh_fuel    = 7.0
coal_ef_tCO2_per_MWh_fuel      = 0.36
biomass_price_nzd_per_MWh_fuel = 35.0
biomass_ef_tCO2_per_MWh_fuel   = 0.0059
elec_price_flat_nzd_per_MWh    = 105.0
ets_price_nzd_per_tCO2         = 30.0

[signals.epochs."2024"]
year_start = 2024
year_end   = 2026
coal_price_nzd_per_MWh_fuel    = 7.0
coal_ef_tCO2_per_MWh_fuel      = 0.36
biomass_price_nzd_per_MWh_fuel = 35.0
biomass_ef_tCO2_per_MWh_fuel   = 0.0059
elec_price_flat_nzd_per_MWh    = 145.0
ets_price_nzd_per_tCO2         = 60.0

[signals.epochs."2027"]
year_start = 2027
year_end   = 2034
coal_price_nzd_per_MWh_fuel    = 7.0
coal_ef_tCO2_per_MWh_fuel      = 0.36
biomass_price_nzd_per_MWh_fuel = 38.0
biomass_ef_tCO2_per_MWh_fuel   = 0.0059
elec_price_flat_nzd_per_MWh    = 130.0
ets_price_nzd_per_tCO2         = 70.0

[signals.epochs."2035"]
year_start = 2035
year_end   = 2050
coal_price_nzd_per_MWh_fuel    = 10.0
coal_ef_tCO2_per_MWh_fuel      = 0.36
biomass_price_nzd_per_MWh_fuel = 42.0
biomass_ef_tCO2_per_MWh_fuel   = 0.0059
elec_price_flat_nzd_per_MWh    = 110.0
ets_price_nzd_per_tCO2         = 90.0





